### PR TITLE
Fix QPainterPath path has incomplete type and cannot be defined

### PR DESCRIPTION
**Pull request by ozzdemir**
While building the jsk_rviz_plugins from source on a ubuntu 22.04 system in a catkin workspace, had the following error message. And to fix it, included the _QPainterPath_ header.

> jsk_visualization/jsk_rviz_plugins/src/overlay_diagnostic_display.cpp:388:18: error: aggregate ‘QPainterPath path’ has incomplete type and cannot be defined
>   388 |     QPainterPath path;

### CODE REVIEW

**Comment by k-okada** [comment]
Thank you for contribution, is this work on old ubuntu ? like 18.04 or 20.04?

**Comment by ozzdemir** [comment]
I was able to test it on 18.04 also, and observed no discrepancy and was able to successfully build the packages.
